### PR TITLE
Publish data set react

### PR DESCRIPTION
**Pull request by jernejpregelj**

### CODE REVIEW

**Comment by ttmc** [comment]
I hope to review this PR this afternoon. Travis is failing on some Markdown styling things. I will push a commit (or more) to get it passing.

**Comment by kremalicious** [comment]
@jernejpregelj `npm run format` is your friend :-) https://github.com/oceanprotocol/docs#linting--formatting

**Comment by ttmc** [comment]
@kremalicious For some reason, running the docs locally is now failing (when I do `npm start`). I updated node to v10.14.1 (for the tutorial). I wonder if that might be the problem. Could you take a look at what version of node you are running for the docs?

**Comment by ttmc** [comment]
I used nvm to install node v8.14.0 for the docs build terminal and now they build locally...

File: content/tutorials/react-setup.md [hunk 1]
```diff
@@ -0,0 +1,102 @@
+---
+title: React App Setup
+description: Tutorial to set up a basic React app that uses squid-js.
+---
+
+This tutorial shows how you can build a basic [React](https://reactjs.org/) app that uses the squid-js JavaScript package to publish a data set, get a data set, and more.
```
Comment (kremalicious) [inline content/tutorials/react-setup.md]:
```suggestion
This tutorial shows how you can build a basic [React](https://reactjs.org/) app with [Create React App](https://github.com/facebook/create-react-app) that uses the squid-js JavaScript package to publish a data set, get a data set, and more.
```

Also, that intro probably should be the `description` value in the frontmatter above.

File: content/tutorials/react-setup.md [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+
+- `nodejs` >= 10 is installed. You can check using `node -v`
+- `npm` >= 5.2 is installed. You can check using `npm -v`
+- Running all the services started by `./start_ocean.sh --no-pleuston --local-pond-node` in [oceanprotocol/docker-images](https://github.com/oceanprotocol/docker-images) running with
+- Using browser with [MetaMask](https://metamask.io/) and some Ether in your account (for the network you're connected to). See [the tutorial about getting Ether and Ocean Tokens for testnets](/tutorials/get-ether-and-ocean-tokens/).
+
+## Tutorial Steps
+
+1. Run `npx create-react-app marketplace` in you terminal. This will create a folder named `marketplace` with a boilerplate React app.
+2. Move to your app directory with `cd marketplace` and run `yarn add @oceanprotocol/squid web3`. This adds the OceanProtocol and Web3 packages to the app.
```
Comment (kremalicious) [inline content/tutorials/react-setup.md]:
```suggestion
2. Move to your app directory with `cd marketplace` and run `npm install @oceanprotocol/squid web3`. This adds the Ocean Protocol JavaScript library and Web3 packages to the app.
```

File: content/tutorials/react-setup.md [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+3. At this point you can already run `yarn start` which starts the app in your browser at [localhost:3000](http://localhost:3000).
```
Comment (kremalicious) [inline content/tutorials/react-setup.md]:
```suggestion
3. At this point you can already run `npm start` which starts the app in your browser at [localhost:3000](http://localhost:3000).
```

File: content/tutorials/react-setup.md [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+       )
+     }
+   }
+   export default App
+   ```
+
+5. Below the `import './App.css'` line, let's import the packages we installed, set up web3 and unlock MetaMask accounts (if locked):
+
+   ```javascript
+   import { Ocean } from '@oceanprotocol/squid/dist/node/squid'
```
Comment (kremalicious) [inline content/tutorials/react-setup.md]: is being so specific now required after the recent changes in squid-js? Otherwise should be just `import { Ocean } from '@oceanprotocol/squid`

Comment (ttmc) [reply content/tutorials/react-setup.md]: @jernejpregelj You should probably answer that one.

File: content/tutorials/react-setup.md (hunk 1 above)
Comment (ttmc) [reply content/tutorials/react-setup.md]: @jernejpregelj Because you created this pull request, only you can accept these "Suggested changes" (via the GitHub user interface).

File: content/tutorials/react-setup.md (hunk 4 above)
Comment (jernejpregelj) [reply content/tutorials/react-setup.md]: @kremalicious 
Which recent changes? We still need to provide web3 object in config and unlock metamask for website if we want to register assets.

**Comment by ttmc** [comment]
@kremalicious I got `npm start` to work with node v10.14.1 by doing `npm rebuild` then `npm install` first. `npm install` by itself wasn't enough.

File: content/tutorials/react-setup.md (hunk 4 above)
Comment (kremalicious) [reply content/tutorials/react-setup.md]: I mean only the new build output for node & browser and just referring to the long import path `@oceanprotocol/squid/dist/node/squid` which should simply be `@oceanprotocol/squid`

**Comment by kremalicious** [comment]
mama-always-said-npm-install-is-like-a-box-of-chocolates-you-never-know-what-youre-gonna-get

**Comment by ttmc** [comment]
I'm done with the copy-editing but I'm not able to fully test the tutorial yet because something is wrong with the running docker-images --- "Failed to load OceanMarket from ocean_poa_net_local Error: Cannot find module './OceanMarket.ocean_poa_net_local.json'"

I saw a similar error about that file being missing when I ran `./start_ocean.sh --no-pleuston --local-pond-node` (on https://github.com/oceanprotocol/docker-images/pull/71/commits/306585118b752ac111673d2a4be5b5eb463d3eaf ). See https://github.com/oceanprotocol/docker-images/pull/71#issuecomment-444805733 

Anyway, I don't think that's a problem with the _tutorial_ so we should be able to merge this PR.

File: content/tutorials/react-setup.md (hunk 4 above)
Comment (jernejpregelj) [reply content/tutorials/react-setup.md]: @kremalicious pushed commits with this fixed.

File: content/tutorials/react-setup.md [hunk 5]
```diff
@@ -40,7 +40,7 @@ This tutorial shows how you can build a basic [React](https://reactjs.org/) app
 5. Below the `import './App.css'` line, let's import the packages we installed, set up web3 and unlock MetaMask accounts (if locked):
 
    ```javascript
-   import { Ocean } from '@oceanprotocol/squid/dist/node/squid'
+   import { Ocean } from '@oceanprotocol/squid'
```
Comment (ttmc) [inline content/tutorials/react-setup.md]: @jernejpregelj This line also occurs in the code listing at the bottom of the page and on the bottom of the /tutorials/react-publish-data-set/ page.

Comment (jernejpregelj) [reply content/tutorials/react-setup.md]: @ttmc pushed commit with fix.

File: content/tutorials/react-setup.md [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+5. Below the `import './App.css'` line, let's import the packages we installed, set up web3 and unlock MetaMask accounts (if locked):
+
+   ```javascript
+   import { Ocean } from '@oceanprotocol/squid'
+   import * as Web3 from 'web3'
+   const web3 = new Web3(window.web3.currentProvider)
+   window.ethereum.enable()
+   ```
+
+6. After the line `class App extends Component {` add the following Ocean initialization with all configuration. All OceanProtocol operations can be executed from this Ocean instance.
```
Comment (kremalicious) [inline content/tutorials/react-setup.md]:
```suggestion
6. At the beginning of your component, create a new Ocean instance with all configuration within the `componentDidMount` lifecycle method. All Ocean Protocol operations can be executed from this Ocean instance.
```

File: content/tutorials/react-setup.md [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+That's it, if you have no errors in your `console.log` then you have successfully initialized an Ocean instance in you brand new React app and you are ready for the next steps in this tutorial.
+
+Here is the full source of `src/App.js` that you should have if you followed this tutorial:
+
+```javascript
+import React, { Component } from 'react'
+import './App.css'
+import { Ocean } from '@oceanprotocol/squid'
+import * as Web3 from 'web3'
+const web3 = new Web3(window.web3.currentProvider)
```
Comment (kremalicious) [inline content/tutorials/react-setup.md]: Just some spacing suggestions to make reading the code a bit more easy

```suggestion

const web3 = new Web3(window.web3.currentProvider)
```

File: content/tutorials/react-setup.md [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+window.ethereum.enable()
+class App extends Component {
```
Comment (kremalicious) [inline content/tutorials/react-setup.md]:
```suggestion

class App extends Component {
```

**Comment by jernejpregelj** [comment]
Fixes added after merge are in #95
